# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-26 18:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentacionescenario',
            name='escenario',
        ),
        migrations.AlterField(
            model_name='presentacionescenario',
            name='nombre',
            field=models.CharField(max_length=100, verbose_name='Nombre de la presentacion'),
        ),
        migrations.AlterField(
            model_name='presentacionescenario',
            name='presentacion',
            field=models.ImageField(upload_to='presentacion'),
        ),
    ]
