# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-11 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserva', '0002_auto_20170831_1602'),
    ]

    operations = [
        migrations.AddField(
            model_name='escenario',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/escenarios'),
        ),
    ]
